### ISSUE TITLE
[Suggestion] VCF sample name

### ISSUE THREAD

**Issue by hmkim** [parklab/NGSCheckMate#1]
In VCF spec, sample id is required.

so, I think the output sample name can pass by sample ID in VCF.

Thanks in advance!

**Comment by ejalicelee** [comment]
Thank you for the suggestion. In BAM/VCF mode, the sample ID in the input VCF file or the VCF file name itself is passed to the output sample name. If this is not clear or what you meant is different from our understanding, feel free to ask us again.

**Comment by hmkim** [comment]
@ejalicelee Thanks for your reply. I meant you said that.
