### ISSUE TITLE
Issues with file names

### ISSUE THREAD

**Issue by zhujack** [parklab/NGSCheckMate#10]
Thanks for the package.  I have been using alternative fastq method.  But the following code often gives me errors:
` python $NCM_HOME/vaf_ncm.py -I $vafDir -O $outDir -N NGSCheckMate`

Traceback (most recent call last):
  File "/home/zhujack/Downloads/NGSCheckMate/vaf_ncm.py", line 638, in <module>
    classifying()
  File "/home/zhujack/Downloads/NGSCheckMate/vaf_ncm.py", line 365, in classifying
    output_matrix_f.write(key[0:key.index('.')])
ValueError: substring not found

Then I found in vaf_ncm.py:

Lines 344-352 have substring [:-4]
Lines 360, 365 also have substring: [0:key.index('.')]

I guess both of the substr do not work for my case.   Your help will be greatly appreciated.

Jack

**Comment by sejooning** [comment]
Hi Jack.
Thank you for using the NGSCheckMate.
Could you check whether there are only vaf files in $vafDir or not.
For using vaf_ncm.py, there should be only vaf files in the input_dir.

Best,
Sejoon Lee

**Comment by zhujack** [comment]
Thanks, Sejoon.  My $vafDir only has symbolic links of the vaf files.

Jack
