### ISSUE TITLE
Pattern files for GRCh38

### ISSUE THREAD

**Issue by anishbhaswanth** [parklab/NGSCheckMate#12]
Hi,

I recently tried using NGSCheckMate tool. I have couple of questions regarding the usage of the tool.

Is there a way to produce pattern files for GRCh38 instead of GRCh37? I only see files belonging to the older version of the reference (GRCh37).

I noticed you have a patterngenerator script, but it needs a BED file with known SNPs. I see you already have the BED file for GRCh37, but not for GRCh38. If you can tell me, how this BED file created, that would be helpful as well.

PS: I'm using the tool on RNA-Seq data.

Thanks,
Anish.

**Comment by sejooning** [comment]
Hi Anish,

Thank you for using the NGSCheckMate. Could you please try 'liftOver' (one of UCSC genome browser utilities)to convert hg19 coordinates to hg38? Then you will get the GRCh38 version bed file.

The pattern-generator script is for the alignment-free version (.pt).  We don't need to consider another reference files for human samples, but input files should be FASTQ.

Hope it is helpful for your work.

Best,
Sejoon Lee
