### ISSUE TITLE
single end ChIPseq versus paired end WES

### ISSUE THREAD

**Issue by crazyhottommy** [parklab/NGSCheckMate#2]
Hi,

Can I check single end ChIPseq and paired end WES data (100 bp paired end) from the same patient?
which mode do you recommend?

If I use the fastq mode, how should I set up the -l file?
the other problem is that ChIPseq read is short (37bp). the flanking seq length of the SNP is 21 bp,
should I change it as well?

Thanks!
Tommy

**Comment by sejooning** [comment]
Hi Tommy,

The read length ( 37bp ) is too short for the FASTQ mode, therefore, you
should change the franking sequence length (about 15 bp?). But we couldn't
guarantee the performance in this case.

For the -l ('l'ist_samples) option, you can use an input file format like
as follows:

FORMAT ( paired-end ): FASTQ1 (tab) FASTQ2 (tab) Sample_name (enter)

/data/LSJ_R1.fastq /data/LSJ_R2.fastq LSJ

FORMAT ( single-end ): FASTQ (tab) Sample_name (enter)
/data/LSJ.fastq  LSJ



Therefore, your input file (fastq_list.txt) maybe include:

/data/WES1_R1.fastq /data/WES1_R2.fastq WES1
/data/WES2_R1.fastq /data/WES2_R2.fastq WES2
/data/WES3_R1.fastq /data/WES3_R2.fastq WES3
/data/ChIP1.fastq  ChIP1
/data/ChIP2.fastq  ChIP2



You can run the NGSCheckMate like as below (-L 15 is not recommended
(default 21), but your case is too short read length):
python ncm_fastq.py -l fastq_list.txt -O output -N ChIP_batch -p 4 -L 15
-pt SNP/SNP.pt


For the alternative way, you can use the "ngscheckmate_fastq" and
"vaf_ncm.py" as described in the manual.

Thank you,
Best,
Sejoon Lee

Sejoon Lee, Ph. D.

T.  +82-70-4639-6619

F.  +82-2-445-8705

2017-04-10 7:11 GMT+09:00 Ming Tang <notifications@github.com>:

**Comment by crazyhottommy** [comment]
Thank you for your reply! 
do you think if I call mutations with mutect on the single end 37bp fastq and then use bam mode or vcf mode is better than fastq mode?

**Comment by sejooning** [comment]
I think it's better to use BAM or VCF mode for these short read length cases. Thank you.
