### ISSUE TITLE
scripts not executable

### ISSUE THREAD

**Issue by 0xaf1f** [parklab/NGSCheckMate#7]
The way you've set up your program requires executing the python scripts as

```
python ncm.py ...
```

whereas if you add a shebang line and mark them executable, these programs can be executed directly (`ncm.py ...`) once the installation directory is added to `PATH`.

You can just do:
```
sed -i '1 i\#!/usr/bin/env python2' *.py
chmod +x *.py
```

Also, the .py suffix on the file names is not really needed in this case. It unnecessarily exposes implementation details to the user.

**Comment by sejooning** [comment]
Thank you for your good suggestions. We will try to apply this in the next version.
