### ISSUE TITLE
prioritize ./ncm.conf over $NCM_HOME/ncm.conf

### ISSUE THREAD

**Issue by 0xaf1f** [parklab/NGSCheckMate#8]
installing this centrally, it seems to make more sense to be able to set defaults in `$NCM_HOME/ncm.conf` that other users can override by copying it and setting their preferred reference sequence. Currently, `./ncm.conf` is only read if the `NCM_HOME` variable isn't set.

**Comment by 0xaf1f** [comment]
although I guess if the program is using data specific to version 37, there's no reason to set a different reference. Feel free to close this.

**Comment by sejooning** [comment]
Thank you for your good suggestions. We didn't pay attention to consider settings for multiple users. We are using version 37 now, but we will update this if other versions are added.

Best,
Sejoon Lee
